### ISSUE TITLE
no such file or directory, mkdir 'undefined/DownloadReleaseArtifactTask'

### ISSUE THREAD

**Issue by metareven** [huserben/PublishReleaseArtifactsExtension#2]
I cannot get this to work at all. When trying to download the artifact I only get the error message:
```
##[error]ENOENT: no such file or directory, mkdir 'undefined/DownloadReleaseArtifactTask'
```
This is how my task looks like:
![image](https://user-images.githubusercontent.com/1016620/77758094-ac52ba80-7032-11ea-943b-680dbd011274.png)

**Comment by huserben** [comment]
Hi @metareven 

it looks like the task cannot find the environment variable for the working directory.
Are you using macOS or ubuntu as build agent?

Could you check the _Initialize job_ task log and see what variables are defined?
Normally there should be a _SYSTEM_DEFAULTWORKINGDIRECTORY_ variable defined.

**Comment by metareven** [comment]
I am using an Ubuntu agent.
From the initialize job task log I can see this output:
[SYSTEM_DEFAULTWORKINGDIRECTORY] --> [/home/vsts/work/r1/a]

**Comment by huserben** [comment]
Hi @metareven 

Thanks for the info.
I will try to reproduce the issue then with an ubuntu agent on my environment so I can do further analysing of the problem.

Once I have more information I will let you know here.

**Comment by huserben** [comment]
Hi @metareven 

Good news, I managed to fix the issue and published a new version.
It seems like it was a problem due to the different handling of the environment variables between Windows and Linux.

Thanks for bringing this to my attention, I know enhanced my test pipeline to include not only windows agents but also run the task with both Ubunut and MacOs agents.

Please let me know if it works now for you with the newest version.

**Comment by huserben** [comment]
Closed due to inactivity
